<?php

return [
    '/news' => \Simflex\Core\Component\Stub\NewsStub::class,
    '/' => \App\Extensions\Content\Content::class,
    '/catalog' => \App\Extensions\Catalog2\Component\Catalog::class,
    '/reviews' => \App\Extensions\Catalog\Component\Review::class,
    '/question' => \App\Extensions\Catalog2\Component\Question::class,
    '/qs' => \App\Extensions\Catalog\Component\Search::class,
    '/cart' => \App\Extensions\Catalog2\Component\Cart::class,
    '/auth' => \App\Extensions\Catalog2\Component\Auth::class,
    '/user/order' => \App\Extensions\Catalog2\Component\Order::class,
    '/user/orders' => \App\Extensions\Catalog2\Component\Order::class,
    '/user' => \App\Extensions\Catalog2\Component\User::class,
    '/brand' => \App\Extensions\Catalog2\Component\Catalog::class,
    '/search' => \App\Extensions\Catalog2\Component\Catalog::class,
    '/filter' => \App\Extensions\Catalog2\Component\Catalog::class,
    '/fav' => \App\Extensions\Catalog\Component\Fav::class,
    '/favorite' => \App\Extensions\Catalog2\Component\Catalog::class,
    '/compare' => \App\Extensions\Catalog\Component\Compare::class,
//    '/refund' => \App\Extensions\Catalog\Component\Refund::class,
    '/blog' => \App\Extensions\Blog\Component\Blog::class,
    '/past' => \App\Extensions\Catalog2\Component\Catalog::class,
    '/import' => \App\Extensions\Import\Component\Import::class,
    '/form' => \App\Extensions\Form\Component\AjaxForm::class,
    '/promotions' => \App\Extensions\Promotion\Component\Promotion::class,
    '/1c/sync'  => \App\Extensions\Onec\api\SyncEndpoint::class,
    '/checkout/make' => \App\Extensions\Catalog2\Component\Checkout::class,
];